# Generated by Django 5.1.4 on 2025-01-12 23:20

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.tools.formats
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.EmailField(help_text='Required. Must be a valid email address.', max_length=254, verbose_name='e-mail')),
                ('is_active', models.BooleanField(default=True, help_text='Determines whether the user can login.', verbose_name='Active User')),
                ('is_staff', models.BooleanField(default=False, help_text='Determines whether the user can login to the admin site.', verbose_name='Staff Status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the user account was created.', verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Required. Legal first name.', max_length=250, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text='Leave blank if no middle name.', max_length=250, verbose_name='Middle Name')),
                ('last_name', models.CharField(help_text='Required. Legal last name.', max_length=250, verbose_name='Last Name')),
                ('display_name', models.CharField(blank=True, help_text='Optional: Enter the name exactly as it should be displayed.', max_length=250, verbose_name='Display Name')),
                ('profile_picture', models.ImageField(blank=True, help_text="Should clearly show the user's face.", upload_to=users.tools.formats.upload_path.profile_picture, verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
